name: qr_code_manager_flutter
description: Handle Qr Barcode operations in a simple way with Qr Code Manager.
version: 1.0.0
authors:
  - Emre Karataş
homepage: https://github.com/oneframemobile/barcode-manager-flutter

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^3.1.0
  barcode_scan: ^2.0.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
